-- MySQL Script generated by MySQL Workbench
-- Sat Jul 15 18:26:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema DB_emcash
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_emcash
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_emcash` DEFAULT CHARACTER SET utf8 ;
USE `DB_emcash` ;

-- -----------------------------------------------------
-- Table `DB_emcash`.`triangulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_emcash`.`triangulo` (
  `idtriangulo` INT NOT NULL AUTO_INCREMENT,
  `baseTri` FLOAT NOT NULL,
  `alturaTri` FLOAT NOT NULL,
  `areaTri` FLOAT NOT NULL,
  PRIMARY KEY (`idtriangulo`),
  UNIQUE INDEX `idtriangulo_UNIQUE` (`idtriangulo` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_emcash`.`retangulo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_emcash`.`retangulo` (
  `idretangulo` INT NOT NULL AUTO_INCREMENT,
  `baseRet` FLOAT NOT NULL,
  `alturaRet` FLOAT NOT NULL,
  `areaRet` FLOAT NOT NULL,
  PRIMARY KEY (`idretangulo`),
  UNIQUE INDEX `idretangulo_UNIQUE` (`idretangulo` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
